### ISSUE TITLE
Extend the PINN function to accept only one boundary condition

### ISSUE THREAD

**Issue by juesuarezca** [ComputationalRadiationPhysics/NeuralSolvers#19]
the function PINNFramewrok.PINN(.., boundary_condition,...) only accepts as input argument for boundary_condition elements  of the form boundary_condition= [bc1,bc2,.. ], but even for only one bc it requires the input to be [bc]. Otherwise it raises 'KeyError' because it cannot call the bc from its name without the list form.

**Comment by StillerPatrick** [comment]
I was able to resolve the bug with adding the single instance boundary condition to the joinded condition. See the lines below. This will be updated in mid of june.  
```python
                if isinstance(boundary_condition, BoundaryCondition):
                    self.boundary_condition = boundary_condition
                    joined_datasets[boundary_condition.name] = boundary_condition.dataset
```
