### ISSUE TITLE
saving a model leads to an error 

### ISSUE THREAD

**Issue by maxxxzdn** [ComputationalRadiationPhysics/NeuralSolvers#21]
https://github.com/ComputationalRadiationPhysics/NeuralSolvers/blob/2a9457257b35265d219db245eb765c6132559748/PINNFramework/PINN.py#L126

Seems like it tries to get the attribute "hpm_model" of the method "pinn_loss" which leads to an error.

**Comment by StillerPatrick** [comment]
No, the pinn loss is a object that should contain a hpm model inside.
