### ISSUE TITLE
PINN should also accept Setups without boundary condition. 

### ISSUE THREAD

**Issue by StillerPatrick** [ComputationalRadiationPhysics/NeuralSolvers#24]

**Comment by StillerPatrick** [comment]
ok its possible by giving the function an empty list as parameter.

**Comment by bussmann** [comment]
There are ALWAYS boundary conditions.

**Comment by StillerPatrick** [comment]
You are right, but in inverse Problems its needed to exclude boundary conditions.

**Comment by nih23** [comment]
The solution won't be unique though.
