### ISSUE TITLE
Adding an API documentation for new forks of the PINN approach

### ISSUE THREAD

**Issue by StillerPatrick** [ComputationalRadiationPhysics/NeuralSolvers#3]

**Comment by nih23** [comment]
- [ ]  add setter for HPM module in PINN interface (setHPMnetwork)
- [ ] add branching in pde loss in PINN interface => go either into analytical PDE loss or HPM PDE loss
- [ ] rename "initial_loss" into "interpolation_loss"
- [ ] add train method to PINN interface
- [ ] add interface for models within PINN interface => e.g. one/two method should provide additional loss terms (if necessary) for interpolation and PDE learning

**Comment by StillerPatrick** [comment]
Is solved by #7
