### ISSUE TITLE
AttributeError: 'function' object has no attribute 'hpm_model'

### ISSUE THREAD

**Issue by maxxxzdn** [ComputationalRadiationPhysics/NeuralSolvers#30]
https://github.com/ComputationalRadiationPhysics/NeuralSolvers/blob/acb61830c0f93a286b59caeacaa421291b3a76d3/PINNFramework/PINN.py#L323

https://github.com/ComputationalRadiationPhysics/NeuralSolvers/blob/acb61830c0f93a286b59caeacaa421291b3a76d3/PINNFramework/PINN.py#L461

I suppose it has to be 'self.pde_loss.hpm_model' instead of 'self.pinn_loss.hpm_model' since self.pinn_loss is a method

**Comment by StillerPatrick** [comment]
Is fixed and can be used correctly with the next release.
