### ISSUE TITLE
HPM does not support cuda

### ISSUE THREAD

**Issue by maxxxzdn** [ComputationalRadiationPhysics/NeuralSolvers#32]
https://github.com/ComputationalRadiationPhysics/NeuralSolvers/blob/bf9af0a3d23bc156a05a339473a75d0b65d25d5f/PINNFramework/PINN.py#L97

I feel like there should be a line sending the model to cuda if needed.

**Comment by StillerPatrick** [comment]
At the moment the framework is designed such that the model has to be moved by the user. But you are right. maybe its a good idea to move to model by the framework.
