### ISSUE TITLE
The for loops for pretraining and main training are ignored

### ISSUE THREAD

**Issue by ahmedemam576** [ComputationalRadiationPhysics/NeuralSolvers#36]
when choosing extremely small no. of samples , which lead that the len(no._of batches) of the dataset which is fed to the dataloader to be equal to zero, which makes the iteration loop to for i in range( 0,0, step):  .. thats why the looping didn't work and the ic_loss wasn't calculated at the first place.
i would suggest creating a warning message when choosing a no. of samples which can make the length of the datasets yields to zero after  the using of "//" operator.

the for loops are found in line 503 and 518 in the pinn.fit () function in the pinn.py file

**Comment by StillerPatrick** [comment]
Will be fixed with pullrequest #40
