### ISSUE TITLE
HPM model is not sent to cuda device

### ISSUE THREAD

**Issue by maxxxzdn** [ComputationalRadiationPhysics/NeuralSolvers#37]
Here, the interpolation model is sent to cuda():

https://github.com/ComputationalRadiationPhysics/NeuralSolvers/blob/ae913e9a9aaa1b9c5e4c86bbd3bde5b727c26e5a/PINNFramework/PINN.py#L70

Meanwhile, I could not find such a line for the hpm model.

**Comment by StillerPatrick** [comment]
Is resolved by your PR.
